# Generated by Django 2.2.3 on 2021-12-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(blank=True, help_text='Leave blank or start with http(s)://', verbose_name='website'),
        ),
    ]
